import { StreamType } from '../StreamCard';

export const EMPTY_FOLLOWED_LIVE_STREAMS: StreamType[] = [
  {
    id: '1',
    streamImageUrl: null,
    countValue: '0',
    avatar: null,
    name: '',
    title: '',
    category: '',
    chips: [],
  },
  {
    id: '2',
    streamImageUrl: null,
    countValue: '0',
    avatar: null,
    name: '',
    title: '',
    category: '',
    chips: [],
  },
  {
    id: '3',
    streamImageUrl: null,
    countValue: '0',
    avatar: null,
    name: '',
    title: '',
    category: '',
    chips: [],
  },
  {
    id: '4',
    streamImageUrl: null,
    countValue: '0',
    avatar: null,
    name: '',
    title: '',
    category: '',
    chips: [],
  },
  {
    id: '5',
    streamImageUrl: null,
    countValue: '0',
    avatar: null,
    name: '',
    title: '',
    category: '',
    chips: [],
  },
];
